language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - libpq-dev

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

before_script:
  - touch dataserv.db

script:
  - coverage run --source="dataserv" setup.py test

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
